import { Colors } from './colors'

export const interests = [
  {
    id: 0,
    fillColor: '#5BD8FF',
    title: 'Спорт',
    icon: 'basketball',
    iconType: 'Ion',
  },
  {
    id: 1,
    fillColor: '#EF4A4A',
    title: 'Музыка',
    icon: 'musical-notes',
    iconType: 'Ion',
  },
  {
    id: 2,
    fillColor: '#F1F449',
    title: 'Еда',
    icon: 'pizza',
    iconType: 'Ion',
  },
  {
    id: 3,
    fillColor: '#FFA030',
    title: 'Алкоголь',
    icon: 'beer',
    iconType: 'Ion',
  },
  {
    id: 4,
    fillColor: '#2421DF',
    title: 'Религия',
    icon: 'book',
    iconType: 'Ion',
  },
  {
    id: 5,
    fillColor: '#B48100',
    title: 'Чтение',
    icon: 'library',
    iconType: 'Ion',
  },
  {
    id: 6,
    fillColor: '#308639',
    title: 'Кино',
    icon: 'videocam',
    iconType: 'Ion',
  },
  {
    id: 7,
    fillColor: '#00FF19',
    title: 'Прогулки',
    icon: 'walk',
    iconType: 'Ion',
  },
  {
    id: 8,
    fillColor: '#F318D0',
    title: 'Шоппинг',
    icon: 'bag-personal',
    iconType: 'Material',
  },
  {
    id: 9,
    fillColor: '#A01D1D',
    title: 'Игры',
    icon: 'game-controller',
    iconType: 'Ion',
  },
  {
    id: 10,
    fillColor: '#5F6AA4',
    title: 'Фото',
    icon: 'camera',
    iconType: 'Ion',
  },
  {
    id: 11,
    fillColor: '#C89D2E',
    title: 'Авто',
    icon: 'car',
    iconType: 'Ion',
  },
  {
    id: 12,
    fillColor: '#7E7E7E',
    title: 'Вейп',
    icon: 'smoke',
    iconType: 'Material',
  },
  {
    id: 13,
    fillColor: '#77B6BE',
    title: 'Рисование',
    icon: 'color-palette',
    iconType: 'Ion',
  },
  {
    id: 14,
    fillColor: '#5FD679',
    title: 'Скейт',
    icon: 'skateboard',
    iconType: 'Material',
  },
  {
    id: 15,
    fillColor: '#936FE1',
    title: 'Велосипед',
    icon: 'bicycle',
    iconType: 'Ion',
  },
  {
    id: 16,
    fillColor: '#ACAF00',
    title: 'Самокат',
    icon: 'scooter',
    iconType: 'Material',
  },
  {
    id: 17,
    fillColor: '#A0399C',
    title: 'Клубы',
    icon: 'wine',
    iconType: 'Ion',
  },
  {
    id: 18,
    fillColor: '#0688FF',
    title: 'Рыбалка',
    icon: 'fish',
    iconType: 'Material',
  },
  {
    id: 19,
    fillColor: '#FFD600',
    title: 'Животные',
    icon: 'paw',
    iconType: 'Material',
  },
  {
    id: 20,
    fillColor: '#E97B7B',
    title: 'Азарт',
    icon: 'cards-playing-spade',
    iconType: 'Material',
  },
  {
    id: 21,
    fillColor: '#000',
    title: 'Другое',
    icon: 'help',
    iconColor: Colors.white,
    iconType: 'Ion',
  },
]
