export enum Screens {
  home = 'Home',
  city = 'City',
  menu = 'Menu',
  buses = 'Buses',
  settings = 'Settings',
  welcome = 'Welcome',
  signUp = 'Sign Up',
  signIn = 'Sign In',
  authVerification = 'Auth Verification',
  emailVerification = 'Email Verification',
  acquaintanceAbout = 'Acquaintance: About',
  acquaintanceAddress = 'Acquaintance: Address',
  acquaintanceBirthDate = 'Acquaintance: Date Screen',
  acquaintanceFinish = 'Acquaintance: Finish',
  acquaintanceInterests = 'Acquaintance: Interests',
  acquaintanceStart = 'Acquaintance: Start',
  acquaintanceNames = 'Acquaintance: Names',
  completeScreen = 'Complete Screen',
  myInformation = 'My Information',
  myInterests = 'My Interests',
  placesToVisitComments = 'Places To Visit: Comments',
  placestoVisitDetails = 'Places To Visit: Details',
  placesToVisitEditComments = 'Places To Visit: Edit Comment',
  placesToVisitPhoto = 'Places To Visit: Photo',
  placesToVisitPhotos = 'Places To Visit: Photos',
  sendError = 'Send Error',
}

export enum Navigators {
  bottomTabs = 'bottomTabs',
}
